services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      FAISS_PATH: "/data/index.faiss"
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: