services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Chatbot_npc_gen
    env_file:
      - ./App/.env
    ports:
      - "8000:8000"
    volumes:
      - ./App:/app/App
      - ./App/Data:/app/App/Data
    depends_on:
      - mongo
    command: uvicorn App.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB:-npcdb}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mongo_data: {}